feat(zeroize): added zeorizing to `Felt`
starknet-io/types-rs pull request #100
Opened 2024-10-09 16:25 UTC by Trantorian1

This is feature-gated behind the `zeroing` flag

# Pull Request type

- Feature

## What is the current behavior?

[`Felt`](https://github.com/starknet-io/types-rs/blob/7ef30234da7957f7585ea832d57d13083c76995c/crates/starknet-types-core/src/felt/mod.rs#L45) provides no option to zeroize its memory, which can be an issue when dealing with sensitive cryptographic information such as private keys.

Resolves: #99 

## What is the new behavior?

- Implemented zeroizing for `Felt` through the [`zeroize`](https://crates.io/crates/zeroize) crate. While `zeroize` is not used directly, Felt implements manually the `Zeroize` trait in the hopes of making this behavior more 'standard'. This has been gated behind the `zeroing` feature. 

> [!NOTE]
> Contrarily to `zeroize`, this is done using safe rust by leveraging `core::mem::take` to replace the in-memory representation of a felt with its default value of `Felt::ZERO`.

## Does this introduce a breaking change?

No. While the `zeroing` feature has been added to `default`, zeroing has not been implemented on drop, both because this would interfere with the `Copy` trait of `Felt` but also because it seems like it should be up to the end user to determine when they are dealing with sensitive information.

2025-01-23 17:07 UTC, tdelabro requested changes

2025-01-23 17:07 UTC, tdelabro commented on crates/starknet-types-core/Cargo.toml
> +zeroing = ["zeroize"]
zeroing = ["dep:zeroize"]
in ordr to disable the implicit feature.
https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies

Currently you have two features available 
`zeroing` the one you defined
and 
`zeroize` from the default behaviour of `optional = true`

2025-01-23 17:07 UTC, tdelabro commented on crates/starknet-types-core/Cargo.toml
> +zeroing = ["zeroize"]
for this types of feature that just depend on one single crate, I tend to name the feature by the crate name. Here `zeroize` rather than `zeroing`. Wdyt?

2025-01-23 17:07 UTC, tdelabro commented on crates/starknet-types-core/src/felt/mod.rs
> +mod zeroing {
you don't really need to create a new module here. Or if you do, it should be behind the feature flag. Here it will happen in the path, even if it is empty, when the feature is not enabled

2025-01-23 17:07 UTC, tdelabro commented on crates/starknet-types-core/src/felt/mod.rs
> +mod zeroing {
I would recommend to make it a file. `zeroize.rs`. And put `mod` import behind the feature flag in felt/mod.rs

2025-01-23 17:07 UTC, tdelabro commented on crates/starknet-types-core/src/felt/mod.rs
> +    impl zeroize::Zeroize for Felt {
Can't you just use leverage https://docs.rs/zeroize/latest/zeroize/trait.DefaultIsZeroes.html?

2025-01-23 17:07 UTC, tdelabro commented on crates/starknet-types-core/src/felt/mod.rs
> +    }
move this tests to the new file too

2025-03-24 08:35 UTC, Trantorian1 commented on crates/starknet-types-core/src/felt/mod.rs
> +    impl zeroize::Zeroize for Felt {
Yep you're right. I was not aware of this trait, thanks for the info!

2025-03-24 08:35 UTC, Trantorian1 commented on crates/starknet-types-core/src/felt/mod.rs
> +    }
Same as above, I feel like moving this to a separate file would be overkill? Wdyt?

2025-03-24 17:04 UTC, tdelabro commented on crates/starknet-types-core/src/felt/mod.rs
> +mod zeroing {
felt/mod.rs is a beefy 2k lines of code. It's already painful to navigate it

2025-03-24 17:04 UTC, tdelabro commented on crates/starknet-types-core/src/felt/mod.rs
> +mod zeroing {
But it's just a matter of taste of preference. So I won't force mine on the codebase

2025-03-24 17:05 UTC, tdelabro approved these changes

2025-03-24 17:06 UTC, tdelabro commented
@pefontana @dan-starkware @maciejka @0xLucqs can we get a second review?

2025-03-24 22:28 UTC, 0xLucqs requested changes

2025-03-24 22:28 UTC, 0xLucqs commented on crates/starknet-types-core/Cargo.toml
> +default = ["std", "serde", "curve", "num-traits", "zeroize"]
are we sure we want that by default ?

2025-03-24 22:28 UTC, 0xLucqs commented on crates/starknet-types-core/src/felt/mod.rs
> +    use super::*;
do you need anything else than `Felt`?

2025-03-24 22:35 UTC, tdelabro commented on crates/starknet-types-core/Cargo.toml
> +default = ["std", "serde", "curve", "num-traits", "zeroize"]
indeed, maybe not

2025-03-26 07:53 UTC, Trantorian1 commented
Applied your suggestions @0xLucqs, thanks catching that!

2025-03-26 09:54 UTC, 0xLucqs approved these changes

2025-03-26 16:57 UTC, merged