feat: add checked add/mul/sub
starknet-io/types-rs pull request #108
Opened 2024-12-25 23:58 UTC by tdelabro

## What is the current behavior?

Checked operation traits are not available for Felt.
## What is the new behavior?

Following traits are implemented 
- CheckedAdd
- CheckedMul
- CheckedSub

## Does this introduce a breaking change?

No

## Other information

It would make sense to impl CheckedDiv too. But the trait requires that `Div` be implemented. Something we chose to not do so far. It may be worth reconsidering this.

2025-01-23 16:04 UTC, 0xLucqs approved these changes
against my will

2025-01-28 07:33 UTC, cchudant requested changes

2025-01-28 07:33 UTC, cchudant commented on crates/starknet-types-core/src/felt/num_traits_impl.rs
> +        if res < *self {
I believe that implementation is wrong,
Felt::TWO * Felt::MAX will probably not work the same way as `2u32.wrapping_add(u32::MAX)` returns 1

2025-02-03 12:40 UTC, tdelabro commented on crates/starknet-types-core/src/felt/num_traits_impl.rs
> +        if res < *self {
You are right. It should check against `max(self, v)`

I fixed it and added a test

2025-02-03 12:44 UTC, tdelabro commented on crates/starknet-types-core/src/felt/num_traits_impl.rs
> +        if res < *self {
but now there is a bug for mul by zero

2025-02-03 12:52 UTC, tdelabro commented on crates/starknet-types-core/src/felt/num_traits_impl.rs
> +        if res < *self {
fixed

2025-02-03 15:13 UTC, cchudant requested changes
I do not believe this is a good enough check for the CheckedMul.
Here is another case:
```rs
println!("{:?}", Felt::from(u128::MAX).checked_mul(&Felt::from(u128::MAX)));
```
This I believe overflows, but does not return None.

Checking for overflow on the multiply operation after the fact is tricky. I don't know any way to do it if we don't have the divide operation.

2025-02-11 20:38 UTC, closed without merging