Implement felt to bigint functions
starknet-io/types-rs pull request #23
Opened 2023-12-11 18:44 UTC by pefontana

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

## Other information

2023-12-18 09:23 UTC, LucasLvy requested changes

2023-12-18 15:04 UTC, Oppen commented
Since we now have the types in the same crate, would it make sense to implement the `From<Felt> for BigUint` and the like?

2023-12-18 15:55 UTC, LucasLvy commented
Maybe something like `From<Felt> for BigUint && BigInt` and a function implemented on the felt struct `to_biguint` idk, i don't really like this kind of helper functions, or maybe in a utils crate

2023-12-19 19:50 UTC, pefontana commented on crates/starknet-types-core/src/felt.rs
> +    }
Yes, I thought about doing something like that, but I actually think that the `to_bigint() `and `to_biguint() `methods are more explicit and readable

2023-12-19 19:51 UTC, pefontana commented
> Maybe something like `From<Felt> for BigUint && BigInt` and a function implemented on the felt struct `to_biguint` idk, i don't really like this kind of helper functions, or maybe in a utils crate

Sure @LucasLvy !
Done!

2023-12-20 13:03 UTC, LucasLvy approved these changes

2023-12-20 13:03 UTC, merged