Add support for the v0.6 of the Starknet API
starknet-io/types-rs pull request #35
Opened 2024-01-12 12:35 UTC by nils-mathieu

This pull request adds support for the 0.6 version of the specification.

2024-01-12 12:36 UTC, nils-mathieu commented
wait was there a rebase? Why are those commits not found

Oooh, no. I did forget to pull.

2024-01-12 13:45 UTC, LucasLvy approved these changes

2024-01-12 13:46 UTC, LucasLvy requested changes
Upgrade the package version to the rpc version plz

2024-01-22 13:36 UTC, LucasLvy approved these changes

2024-01-22 13:36 UTC, merged