chore(rpc): generate latest spec
starknet-io/types-rs pull request #60
Opened 2024-04-18 16:00 UTC by LucasLvy

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

## Other information

2024-06-14 14:20 UTC, LucasLvy reviewed
I think we should require the felt type to impl Debug, Display, Clone, Serialize, Deserialize

2024-06-27 11:02 UTC, tdelabro requested changes

2024-06-27 11:02 UTC, tdelabro commented on crates/starknet-types-rpc/src/v0_7_1/starknet_api_openrpc.rs
> +    pub sequencer_address: F,
Address

2024-06-27 11:02 UTC, tdelabro commented on crates/starknet-types-rpc/src/v0_7_1/starknet_write_api.rs
> +    pub contract_address: Felt,
F or Address

2024-07-23 08:23 UTC, maciejka commented on crates/starknet-types-rpc/src/custom/query.rs
> +pub enum BroadcastedDeclareTxn<F: Default> {
Added V3 related declarations.

2024-07-23 08:23 UTC, maciejka commented on crates/starknet-types-rpc/src/v0_7_1/starknet_api_openrpc.rs
> +// This file was automatically generated by openrpc-gen first, then manually edited.
Now it is fully automatic.

2024-07-23 08:25 UTC, maciejka commented on crates/starknet-types-rpc/src/v0_7_1/starknet_api_openrpc.rs
> +    pub address: F,
It is declared as felt in the spec. I added a pr to the spec: https://github.com/starkware-libs/starknet-specs/pull/213.

2024-07-23 08:26 UTC, maciejka approved these changes

2024-07-23 16:06 UTC, tdelabro approved these changes

2024-07-23 16:06 UTC, merged