Feat: First round of fuzzing tests
starknet-io/types-rs pull request #63
Opened 2024-04-25 14:35 UTC by maciejka

This is based on initial work from @LucasLvy. Adds addition/subtraction, multiplication, division, and formatting fuzzing test.

2024-04-25 15:58 UTC, LucasLvy requested changes
need to test double also

2024-04-25 15:58 UTC, LucasLvy commented on fuzz/felt/fuzz_targets/add.rs
> +    assert_eq!(a + a, Felt::TWO * a, "doubling failed");
do it for b also

2024-04-25 15:58 UTC, LucasLvy commented on fuzz/felt/fuzz_targets/add.rs
> +    assert_eq!(a + max, a - one, "overflow failed");
do it for b also

2024-04-25 15:58 UTC, LucasLvy commented on fuzz/felt/fuzz_targets/add.rs
> +    assert_eq!(zero - a, max - a + one, "overflow failed");
do it for b

2024-04-25 15:58 UTC, LucasLvy commented on fuzz/felt/fuzz_targets/conversions.rs
> +    assert_eq!(felt, Felt::from_bytes_be(&felt.to_bytes_be()), "to_bytes_be failed");
to bits also ?

2024-04-25 15:58 UTC, LucasLvy commented on fuzz/felt/fuzz_targets/conversions.rs
> +    assert_eq!(felt, Felt::from_bytes_le(&felt.to_bytes_le()), "to_bytes_le failed");
from dec string

2024-04-25 15:58 UTC, LucasLvy commented on fuzz/felt/fuzz_targets/conversions.rs
> +    assert_eq!(felt, Felt::from_bytes_be_slice(&felt.to_bytes_be()), "to_bytes_be failed");
to digits

2024-04-25 15:58 UTC, LucasLvy commented on fuzz/felt/fuzz_targets/conversions.rs
> +    assert_eq!(felt, Felt::from_bytes_le_slice(&felt.to_bytes_le()), "to_bytes_be failed");
to bigint (i probably missed some)

2024-05-03 15:51 UTC, LucasLvy requested changes
either separate add and sub or rename add to be add + sub (file names + fuzzing name)

2024-06-04 10:01 UTC, LucasLvy approved these changes

2024-06-06 14:21 UTC, pefontana approved these changes

2024-06-06 14:39 UTC, pefontana commented
Nice one!

2024-06-06 14:39 UTC, merged