Mk/publish
starknet-io/types-rs pull request #86
Opened 2024-07-31 10:33 UTC by maciejka

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

## Other information

2024-07-31 12:01 UTC, 0xLucqs requested changes

2024-07-31 12:01 UTC, 0xLucqs commented on .github/workflows/publish.yml
> +          override: true
use `rustup show` like in the other workflows

2024-07-31 12:01 UTC, 0xLucqs commented on .github/workflows/publish.yml
> +      - master
```suggestion
      - main
```

2024-08-01 10:28 UTC, 0xLucqs requested changes

2024-08-01 10:28 UTC, 0xLucqs commented on .github/workflows/publish.yml
> +          override: true
unresolving as it's still not fixed ?

2024-08-01 10:54 UTC, 0xLucqs approved these changes

2024-08-01 11:23 UTC, tdelabro approved these changes

2024-08-01 11:23 UTC, merged