Bugfix: binary deserialization `Felt`
starknet-io/types-rs pull request #89
Opened 2024-08-21 08:22 UTC by xrvdg

`Felt` supports both human readable and binary serialization, but the binary deserializer was missing. 

## Does this introduce a breaking change?

Yes, but likely no-one is affected by it as deserialization was not working. The (de)serialization is done with bytes rather than sequences. 

## Other information

The serialization and deserialization test have been combined.  Serialization and deserialization should not be tested separately as that makes it too easy to miss a case.

2024-09-05 08:12 UTC, dan-starkware requested changes

2024-09-05 08:12 UTC, dan-starkware commented on crates/starknet-types-core/src/felt/mod.rs
> -        assert_ser_tokens(&Felt::ZERO.readable(), &[Token::String("0x0")]);
Please remove unused imports

2024-09-09 06:47 UTC, dan-starkware approved these changes

2024-09-16 09:13 UTC, 0xLucqs approved these changes

2024-09-16 09:13 UTC, merged