feat: `starknet-types-macros` adding `felt!()`
starknet-io/types-rs pull request #90
Opened 2024-09-09 00:51 UTC by rkdud007

adding `starknet-types-macros` crate to add `felt!()` macro which pretty useful in other libraries e.g starknet-rs ( https://github.com/xJonathanLEI/starknet-rs/blob/660a7323169bbcdaea71b4f0e939631e3aaabd45/starknet-macros/src/lib.rs#L60) 

# Pull Request type

new feature 

## What is the new behavior?

can use `felt!("123")` or `felt!("0xabc")` like this instead have raw method of `Felt` type.

## Does this introduce a breaking change?

no

## Other information

2024-09-09 14:12 UTC, Oppen approved these changes

2025-01-29 14:01 UTC, tdelabro requested changes

2025-01-29 14:01 UTC, tdelabro commented on crates/starknet-types-macros/Cargo.toml
> +    "serde",
Look like the serde feature is no used. Can you remove it or am I missing something?

2025-01-29 14:02 UTC, tdelabro commented
@rkdud007 sorry we are a little late on the review, but this is actually a good contribution to the create. 
Please proceed to rebase and fix it and we will merge it asap

2025-02-01 16:40 UTC, closed without merging

2025-02-01 16:52 UTC, rkdud007 commented
hey @tdelabro while trying to rebase accidentally nuked the codebase totally,,, will be back again sometime

2025-02-03 12:25 UTC, tdelabro commented
hahaha shit happens!!

See you soon